GET http://localhost:5000/notes

###
POST http://localhost:5000/users/
Content-Type: application/json

{
    "name": "Ayudya",
    "email": "Ayudya@gmail.com",
    "gender": "Female",
    "password": "ayudiacantik"
}

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "RyanKNy",
    "email": "rknnyy@gmail.com",
    "gender": "Male",
    "password": "ryankny1"
}

###
POST http://localhost:5000/add-users
Content-Type: application/json

{
    "name": "tes",
    "email": "tes1@tes.com",
    "gender": "Male",
    "password": "12345678"
}

###
POST http://localhost:5000/add-notes
Content-Type: application/json

{
    "name": "Ian",
    "email": "ian@gmail.com",
    "title": "Cihuy",
    "text": "Apasi jir",
    "date": "2025-05-23"
}

###
PUT http://localhost:5000/notes/8
Content-Type: application/json

{
    "name": "Ian",
    "email": "iann@gmail.com",
    "title": "Cihuy",
    "text": "Apasi jir",
    "date": "2025-05-23"
}

###
PUT http://localhost:5000/user/2
Content-Type: application/json

{
    "name": "RyanKNy",
    "email": "RyanKNy@gmail.com",
    "title": "Hari pertama praktikum",
    "text": "Hari pertama praktikum, semoga lancar",
    "date": "2025-03-01"
}

###
DELETE http://localhost:5000/user/2